### ISSUE TITLE
Criação da página sobre

### ISSUE THREAD

**Issue by rodrigovictorio** [rodrigovictorio1/github-master#3]
Vocês poderiam criar uma página de sobre? Agradeço

**Comment by rodrigovictorio1** [comment]
A página já está em produção.

**Comment by rodrigovictorio** [comment]
Obrigado, estou aguardando.
De: ***@***.***>
Enviado:terça-feira, 22 de agosto de 2023 11:16
Para: ***@***.***>
Cc:Rodrigo ***@***.***>; ***@***.***>
Assunto: Re: [rodrigovictorio1/github-master] Criação da página sobre (Issue #3)


A página já está em produção.
